# Generated by Django 5.2.8 on 2025-12-26 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housekg_app', '0002_city_city_name_en_city_city_name_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyimage',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_images', to='housekg_app.property'),
        ),
    ]
